---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
    - f0ee1cc1980474c82a013645508f002dcc801e00db5592f7dd8cd6bdb93c73fe
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
    exclude_fingerprints:
    - 5e98926627c19c41b3b10b1e8a460d58 
    - aa2f5ec79d399a73f0c9ebbabc230aab
    - f9c98e4e5a4730fd291fb5d5c456b464
    - 591f7bb20b6b0e3aa2583570ebf6f998 
    - 5b9b516a73d56d8fa95d0a5f17daf636
    - 9620a0c3759e44e51d1841b2d9349ec7
    - 546044e01acf95e0c6f660329ab86165
    - 36d9446a2f8dc6cc56b1433d165705e1 
    - 261508f2f9b3deec5a88644ea49cc47a
    
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- app/controllers/news_controller.rb
- app/controllers/posts_controller.rb
- coverage/assets/0.10.0/application.js
- features/step_definitions/redcross_steps.rb
- features/step_definitions/web_steps.rb
- features/support/paths.rb
- features/support/selectors.rb
